import Head from "next/head";
import { BsFillMoonStarsFill, BsFillSunFill } from "react-icons/bs";
import { Button } from "@/components/ui/button";
import { RiTwitterXLine } from "react-icons/ri";
import {
  AiFillLinkedin,
  AiFillInstagram,
  AiFillTwitterCircle,
} from "react-icons/ai";
import {
  FaBootstrap,
  FaCss3Alt,
  FaFigma,
  FaGithubSquare,
  FaHtml5,
  FaLaravel,
  FaPhp,
  FaReact,
} from "react-icons/fa";
import { GrMysql } from "react-icons/gr";
import { SiJavascript, SiTailwindcss } from "react-icons/si";
import { FiChevronDown } from "react-icons/fi";
import Image from "next/image";
import profilePic from "../public/pedrolucas-profile-pic.jpg";
import model3d from "../public/3d.png";
// import videoCover from "../public/videoCover.mp4";
import thumbNoisePlayer from "../public/NoisePlayer.png";
import thumbTodoListApp from "../public/TodoListApp.png";
import design from "../public/design-test.png";
import { useState } from "react";
import {
  ChevronDownCircle,
  ChevronUp,
  Hand,
  HandIcon,
  Linkedin,
  MousePointer2,
} from "lucide-react";
import NavItem from "./components/NavItem";
import PortfolioItem from "./components/PortfolioItem";
import UI_Badge from "./components/UI_Badge";
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuIndicator,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  NavigationMenuViewport,
  navigationMenuTriggerStyle,
} from "@/components/ui/navigation-menu";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>pedrolucaslco</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="z-10">
        <nav className="flex justify-between py-6 fixed w-screen z-50 px-4 sm:px-4 md:px-16 lg:px-24 xl:px-40 2xl:px-40">
          <h1 className="text-2xl uppercase font-bold tracking-[.3rem]">
            Pedro Lucas
          </h1>

          <NavigationMenu className="items-center gap-4 hidden md:flex">
            <NavigationMenuList>
              <NavigationMenuItem>
                <Button asChild variant="link">
                  <Link href="#">Home</Link>
                </Button>
              </NavigationMenuItem>

              {/* <NavigationMenuItem>
                <Button asChild variant="link">
                  <Link href="#about-me">About-me</Link>
                </Button>
              </NavigationMenuItem> */}

              <NavigationMenuItem>
                <Button asChild variant="link">
                  <Link href="#portfolio">Portfolio</Link>
                </Button>
              </NavigationMenuItem>

              <NavigationMenuItem>
                <Button asChild>
                  <Link
                    href="https://github.com/pedrolucaslcosta"
                    target="_blank"
                  >
                    GitHub
                  </Link>
                </Button>
              </NavigationMenuItem>
            </NavigationMenuList>
          </NavigationMenu>
        </nav>

        <main
          className="
	  px-4 sm:px-4 md:px-16 lg:px-24 xl:px-40 2xl:px-40
	  transition-all duration-500
	  "
        >
          <section className="h-screen flex flex-col pt-24      ">
          <div className="flex flex-col justify-center h-full items-start gap-8 px-1 lg:px-40">
          <h1 className="text-xl font-bold">hi, I&apos;m Pedro 👋</h1>
              <h1>I&apos;m a frontend developer, designer, and business owner. Currently, I work as a full-stack developer at EasySchool, where I develop and maintain solutions to optimize daily routines for schools.</h1>
			  <div className="text-base sm:text-xl flex justify-start gap-3 sm:gap-4 text-black">
                  <Button asChild>
                    <Link href="mailto:pedrolucaslcosta@gmail.com">
                      Let&apos;s talk
                    </Link>
                  </Button>

                  <Button asChild size="icon" variant="secondary">
                    <Link
                      href="https://www.instagram.com/pedrolucaslco"
                      target="_blank"
                    >
                      <AiFillInstagram className="h-5 w-5" />
                    </Link>
                  </Button>

                  <Button asChild size="icon" variant="secondary">
                    <Link
                      href="https://www.linkedin.com/in/pedrolucaslcosta"
                      target="_blank"
                    >
                      <AiFillLinkedin className="h-5 w-5" />
                    </Link>
                  </Button>

                  <Button asChild size="icon" variant="secondary">
                    <Link
                      href="https://www.x.com/pedrolucaslco"
                      target="_blank"
                    >
                      <RiTwitterXLine />
                    </Link>
                  </Button>
                </div>
            </div>
          </section>
        </main>

        <main className="px-4 sm:px-4 md:px-16 lg:px-24 xl:px-40 2xl:px-40">
          <section className="min-h-screen pb-40">
            <div id="portfolio" className="flex text-center justify-center gap-4 pt-24 pb-16 text-2xl font-bold">
              <span>Portfolio</span>
            </div>
            <div className=" text-slate-100 grid items-center sm:grid-cols-1 grid-cols-1 md:grid-cols-2 lg:grid-cols-2 
			gap-4 lg:gap-2">
              <PortfolioItem
                image={thumbNoisePlayer}
                category={"Design and Development"}
                title={"NoisePlayer"}
                description={
                  "A simple Brown Noise and Ambient Sounds Player to help focus on tasks."
                }
                href={"https://noise-player-pedrolucaslco.vercel.app/"}
                tags={["React.js", "TailwindCSS", "Vite"]}
              />
              <PortfolioItem
                image={thumbTodoListApp}
                category={"Design and Development"}
                title={"To-do List App"}
                description={
                  "A simple CRUD to-do list app for react.js practices."
                }
                href={
                  "https://to-do-list-react-js-pedrolucaslcosta.netlify.app/"
                }
                tags={["React.js", "Vite", "Bootstrap", "Sass"]}
              />
            </div>
          </section>
        </main>

        <footer
          className="
	  px-4 sm:px-4 md:px-16 lg:px-24 xl:px-40 2xl:px-40
	  flex justify-center border-t-2  text-neutral-500 py-8
	  "
        >
          <span>@pedrolucaslco</span>
        </footer>
      </main>
    </div>
  );
}
